### ISSUE TITLE
building on cori

### ISSUE THREAD

**Issue by ndkeen** [polymec/polyamri-dev#10]
cori01% make config
-- The C compiler identification is Intel 16.0.0.20150815
-- The CXX compiler identification is Intel 16.0.0.20150815
-- Check for working C compiler: /opt/cray/craype/2.4.2/bin/cc
-- Check for working C compiler: /opt/cray/craype/2.4.2/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/cray/craype/2.4.2/bin/CC
-- Check for working CXX compiler: /opt/cray/craype/2.4.2/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Building polyamri (v0.7.0)
CMake Error at CMakeLists.txt:20 (include):
  include could not find load file:

    polymec

CMake Error at CMakeLists.txt:22 (message):
  Could not find polymec library.  Please use the polymec=/path/to/polymec
  option.

-- Configuring incomplete, errors occurred!
See also "/project/projectdirs/mpccc/ndk/polyamri-dev/build/Linux-x86_64-cc/CMakeFiles/CMakeOutput.log".
make: *** [config] Error 1
2.180u 12.036s 0:20.24 70.2% 0pf+0w

OK INSTALL claims to try something like:
make config polymec=/project/projectdirs/mpccc/ndk/polymec

**Comment by jjphatt** [comment]
I have verified that this works. You can build/install Polymec into $SCRATCH/polymec (for example) by cloning polymec/polymec-dev and typing:

make config mpi=1 prefix=$SCRATCH/polymec
make mpi=1 install

And then you can build polyamri on top of that install by cd'ing to polyamri-dev and typing

make config polymec=$SCRATCH/polymec
make

Polyamri will use Polymec's configuration options and build all the goodies.
